services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
      - 80:80
      - 22:22
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - ./haproxy/config:/usr/local/etc/haproxy
      - ./haproxy/log:/dev/log
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      # - PUID=501
      # - PGID=20
      - VERSION=docker
    #   - PLEX_CLAIM= #optional
    volumes:
      - ./plex/config:/config
      - ./plex/TV:/tv
      - ./lex/Movies:/movies
    restart: unless-stopped
