services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    # network_mode: host
    ports:
      - 80:80
      - 22:22
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - ./config:/usr/local/etc/haproxy
      - ./log:/dev/log
